[supabase]
url = "https://gljmgptmawpjpwntqtdm.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsam1ncHRtYXdwanB3bnRxdGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjUxNjAsImV4cCI6MjA2MDE0MTE2MH0.tL4Y8XXM2KnLKU0v91DsCy2n0-HdqcmBFi4s5HIznqI"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdsam1ncHRtYXdwanB3bnRxdGRtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDU2NTE2MCwiZXhwIjoyMDYwMTQxMTYwfQ.YIEFwbfZRw9RqzhbyLOAkPgRrUhik2Kl8AuKA636CWI"
